
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const NEW_MESSAGE_RECEIVED = 'NEW_MESSAGE_RECEIVED';
export const NEW_MESSAGE_SENDED = 'NEW_MESSAGE_SENDED';

export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGES_SUCCESS'
export const LOAD_MESSAGE_FAIL = 'LOAD_MESSAGES_FAIL';